
pipeline {

    agent any
    
    environment {
        PASS = credentials('Dockerhub_pass') 
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                      pwd
                    ./pipeline/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./pipeline/jenkins/build/build.sh

                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            steps {
                sh './pipeline/jenkins/test/mvn.sh mvn test'
            }

            post {
                always {
                    junit 'java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Push') {
            steps {
                sh './pipeline/jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './pipeline/jenkins/deploy/deploy.sh'
            }
        }
    }
}
